services:
  app:
    build: .
    container_name: notification-app
    ports:
      - "8080:5000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DATABASE_URL=postgres://postgres:postgres@db:5432/ED-Notif-Sys
      - REDIS_HOST=redis

  db:
    image: postgres:15
    container_name: notification-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ED-Notif-Sys
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: notification-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
